Class {
	#name : #BaselineOfScorch,
	#superclass : #BaselineOf,
	#category : #BaselineOfScorch
}

{
	#category : #baselines,
	#'squeak_changestamp' : 'mad 7/25/2025 21:38'
}
BaselineOfScorch >> baseline: spec [ 
	<baseline>
	spec for: #common do: [
		
	spec  
		description: 'Baseline for Scorch, a library for runtime optimizations';
		author: 'ClementBera'.
	
	spec	
			package: 'Scorching';
			package: 'ScorchingDev' with: [ 
				spec requires: 'Scorching' ];
			package: 'ScorchingTests' with: [ 
				spec requires: #('Scorching') ];
			package: 'ScorchingVMTests' with: [ 
				spec requires: #('Scorching' 'ScorchingDev') ].
	].
]

{ #category : #baselines }
BaselineOfScorch >> project [
	
	| aProject |
	
	aProject := super project.
	aProject loadType: #atomic.
	^ aProject.
	
]
